In [2]:
!pip install pandas numpy openpyxl sqlalchemy pymysql

Requirement already satisfied: pandas in C:\Users\abc\anaconda3\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy in C:\Users\abc\anaconda3\Lib\site-packages (2.4.6)
Requirement already satisfied: openpyxl in C:\Users\abc\anaconda3\Lib\site-packages (3.1.5)
Requirement already satisfied: sqlalchemy in C:\Users\abc\anaconda3\Lib\site-packages (2.0.51)
Requirement already satisfied: pymysql in C:\Users\abc\anaconda3\Lib\site-packages (1.2.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\abc\anaconda3\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\abc\anaconda3\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: et_xmlfile in C:\Users\abc\anaconda3\Lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: greenlet>=1 in C:\Users\abc\anaconda3\Lib\site-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\abc\anaconda3\Lib\site-packages (from sqlalchemy) (4.16.0)
Requirement already satisfied: six>=1.5 in C:\Users\abc\anaconda3\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
# Step 1: Import Libraries

import pandas as pd
import numpy as np

In [4]:
# Step 2: Load Dataset

df = pd.read_excel(r"C:\Users\abc\OneDrive\Desktop\E-Commerce Sales Dashboard using Power BI\Ecommerce_Unclean_2026.xlsx")

In [5]:
# Step 3: Explore the Data 

df.head()

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date
0,ORD1002,30-06-2026,Neha,neha82@gmail.com,9.829008e+09,Delhi,Delhi,Chair,Furniture,4.0,1999.0,NaN,UPI,Pending,03-07-2026
1,ORD1003,03-02-2026,Rohit,rohit45@gmail.com,9.280491e+09,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20,Card,Pending,09-02-2026
2,ORD1004,06-05-2026,Amit,amit6@gmail.com,9.943311e+09,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,5,COD,Returned,08-05-2026
3,ORD1005,20-01-2026,Vikas,vikas51@gmail.com,9.495120e+09,Bengaluru,Karnataka,Laptop,Electronics,NaN,NaN,15,Wallet,Pending,27-01-2026
4,ORD1006,02-04-2026,Rohit,rohit71@gmail.com,9.237332e+09,Pune,Maharashtra,Bottle,Home,NaN,1999.0,,Wallet,Cancelled,07-04-2026

In [6]:
# View Dataset Information

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 524 entries, 0 to 523
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       524 non-null    str
 1   Order_Date     524 non-null    str
 2   Customer_Name  524 non-null    str
 3   Email          524 non-null    str
 4   Phone          502 non-null    float64
 5   City           524 non-null    str
 6   State          524 non-null    str
 7   Product        524 non-null    str
 8   Category       524 non-null    str
 9   Qty            457 non-null    float64
 10  Unit_Price     471 non-null    float64
 11  Discount       455 non-null    object
 12  Payment_Mode   524 non-null    str
 13  Order_Status   524 non-null    str
 14  Delivery_Date  503 non-null    str
dtypes: float64(3), object(1), str(11)
memory usage: 107.3+ KB

In [7]:
# Statistical Summary 

df.describe()

              Phone         Qty   Unit_Price
count  5.020000e+02  457.000000   471.000000
mean   9.544725e+09    2.800875  3168.639066
std    2.636920e+08    1.963974  2969.682209
min    9.104441e+09   -1.000000   499.000000
25%    9.315673e+09    1.000000   999.000000
50%    9.533562e+09    3.000000  1999.000000
75%    9.792574e+09    5.000000  4999.000000
max    9.999074e+09    5.000000  9999.000000

In [8]:
# Dataset Shape

df.shape

(524, 15)

In [9]:
# Step 4: Check Missing Values

df.isnull().sum()

Order_ID          0
Order_Date        0
Customer_Name     0
Email             0
Phone            22
City              0
State             0
Product           0
Category          0
Qty              67
Unit_Price       53
Discount         69
Payment_Mode      0
Order_Status      0
Delivery_Date    21
dtype: int64

In [10]:
# Step 5: Check Duplicates Records

df.duplicated().sum()

np.int64(11)

In [11]:
# Remove Duplicate Records

df.drop_duplicates(inplace=True)

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
# Step 6: Replace Invalid Values(N/A and NULL)

df.replace(
    ["N/A", "NA", "n/a", "NULL", "null", " ", ""],
    np.nan,
    inplace=True
)

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date
0,ORD1002,30-06-2026,Neha,neha82@gmail.com,9.829008e+09,Delhi,Delhi,Chair,Furniture,4.0,1999.0,NaN,UPI,Pending,03-07-2026
1,ORD1003,03-02-2026,Rohit,rohit45@gmail.com,9.280491e+09,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20,Card,Pending,09-02-2026
2,ORD1004,06-05-2026,Amit,amit6@gmail.com,9.943311e+09,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,5,COD,Returned,08-05-2026
3,ORD1005,20-01-2026,Vikas,vikas51@gmail.com,9.495120e+09,Bengaluru,Karnataka,Laptop,Electronics,NaN,NaN,15,Wallet,Pending,27-01-2026
4,ORD1006,02-04-2026,Rohit,rohit71@gmail.com,9.237332e+09,Pune,Maharashtra,Bottle,Home,NaN,1999.0,NaN,Wallet,Cancelled,07-04-2026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,ORD1608,17-02-2026,Rahul,rahul71@gmail.com,9.789375e+09,Lucknow,UP,Mouse,Electronics,4.0,9999.0,NaN,Card,Returned,27-02-2026
520,ORD1609,2026/03/21,Rahul,rahul99@gmail.com,9.552650e+09,Mumbai,Maharashtra,Bottle,Home,2.0,1499.0,NaN,Wallet,Pending,28-03-2026
521,ORD1610,10-04-2026,Rohit,rohit96@gmail.com,9.700117e+09,Jaipur,Rajasthan,Mouse,Electronics,1.0,NaN,NaN,NetBanking,Delivered,16-04-2026
522,ORD1611,11-01-2026,Neha,neha22@gmail.com,9.580304e+09,Jaipur,Rajasthan,Chair,Furniture,3.0,999.0,NaN,COD,Pending,16-01-2026
523,ORD1612,03-03-2026,Vikas,vikas46@gmail.com,9.551158e+09,Jaipur,Rajasthan,Shoes,Fashion,3.0,999.0,5,COD,Cancelled,09-03-2026

In [14]:
# Step 7: Remove Extra Spaces

df=df.apply(lambda x:x.str.strip() if x.dtype=="str" else x)

In [15]:
# Step 8: Standardize Text Format 
# Convert text into Proper Case

df["Customer_Name"] = df["Customer_Name"].str.strip().str.title()
df["City"] = df["City"].str.strip().str.title()
df["State"] = df["State"].str.strip().str.title()
df["Product"] = df["Product"].str.strip().str.title()
df["Category"] = df["Category"].str.strip().str.title()
df["Order_Status"] = df["Order_Status"].str.strip().str.title()

In [16]:
# Step 9: Validate Emails Addresses
# Keep only valid email records

df=df[df["Email"].str.contains("@",na=False)]

In [17]:
df["Email"].isna().sum()

np.int64(0)

In [18]:
# Step 10: Convert Date Columns

df["Order_Date"] = pd.to_datetime(
    df["Order_Date"],
    dayfirst=True,
    errors="coerce"
)

df["Delivery_Date"] = pd.to_datetime(
    df["Delivery_Date"],
    dayfirst=True,
    errors="coerce"
)

In [19]:
# Step 11: Convert Numeric Columns

cols=["Qty","Unit_Price","Discount"]

for c in cols:
    df[c]=pd.to_numeric(df[c],errors="coerce")

In [20]:
df[cols].isna().sum()

Qty            64
Unit_Price     50
Discount      143
dtype: int64

In [21]:
# Step 12: Remove Negative Quantity
df=df[df["Qty"]>0]

In [22]:
# Step 13: Fill Missing Values

df["Discount"] = df["Discount"].fillna(0)
df["Phone"] = df["Phone"].fillna("Unknown")
df["Delivery_Date"] = df["Delivery_Date"].fillna(df["Order_Date"])

In [23]:
# Step 14: Create New Columns 

# TotalSales
df["Sales"]=df["Qty"]*df["Unit_Price"]

In [24]:
df.head()

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date,Sales
0,ORD1002,2026-06-30,Neha,neha82@gmail.com,9829008196.0,Delhi,Delhi,Chair,Furniture,4.0,1999.0,0.0,UPI,Pending,2026-07-03,7996.0
1,ORD1003,2026-02-03,Rohit,rohit45@gmail.com,9280491167.0,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20.0,Card,Pending,2026-02-09,24995.0
2,ORD1004,2026-05-06,Amit,amit6@gmail.com,9943310925.0,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,5.0,COD,Returned,2026-05-08,5997.0
5,ORD1007,2026-02-10,Rahul,rahul82@gmail.com,9517780193.0,Mumbai,Maharashtra,Mouse,Electronics,3.0,499.0,20.0,Wallet,Cancelled,2026-02-18,1497.0
6,ORD1008,2026-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,Up,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,2026-02-27,39996.0

In [25]:
# Net Amount

df["Net_Amount"]=df["Sales"]-(df["Sales"]*df["Discount"]/100)

In [26]:
df

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date,Sales,Net_Amount
0,ORD1002,2026-06-30,Neha,neha82@gmail.com,9829008196.0,Delhi,Delhi,Chair,Furniture,4.0,1999.0,0.0,UPI,Pending,2026-07-03,7996.0,7996.00
1,ORD1003,2026-02-03,Rohit,rohit45@gmail.com,9280491167.0,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20.0,Card,Pending,2026-02-09,24995.0,19996.00
2,ORD1004,2026-05-06,Amit,amit6@gmail.com,9943310925.0,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,5.0,COD,Returned,2026-05-08,5997.0,5697.15
5,ORD1007,2026-02-10,Rahul,rahul82@gmail.com,9517780193.0,Mumbai,Maharashtra,Mouse,Electronics,3.0,499.0,20.0,Wallet,Cancelled,2026-02-18,1497.0,1197.60
6,ORD1008,2026-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,Up,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,2026-02-27,39996.0,39996.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,ORD1608,2026-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,Up,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,2026-02-27,39996.0,39996.00
520,ORD1609,NaT,Rahul,rahul99@gmail.com,9552649559.0,Mumbai,Maharashtra,Bottle,Home,2.0,1499.0,0.0,Wallet,Pending,2026-03-28,2998.0,2998.00
521,ORD1610,2026-04-10,Rohit,rohit96@gmail.com,9700116928.0,Jaipur,Rajasthan,Mouse,Electronics,1.0,NaN,0.0,NetBanking,Delivered,2026-04-16,NaN,NaN
522,ORD1611,2026-01-11,Neha,neha22@gmail.com,9580304152.0,Jaipur,Rajasthan,Chair,Furniture,3.0,999.0,0.0,COD,Pending,2026-01-16,2997.0,2997.00
523,ORD1612,2026-03-03,Vikas,vikas46@gmail.com,9551158398.0,Jaipur,Rajasthan,Shoes,Fashion,3.0,999.0,5.0,COD,Cancelled,2026-03-09,2997.0,2847.15

In [27]:
# Profit (Example :20%)It assumes that your profit margin is 20% of Net Amount.

df["Profit"]=df["Net_Amount"]*0.20

In [28]:
df

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date,Sales,Net_Amount,Profit
0,ORD1002,2026-06-30,Neha,neha82@gmail.com,9829008196.0,Delhi,Delhi,Chair,Furniture,4.0,1999.0,0.0,UPI,Pending,2026-07-03,7996.0,7996.00,1599.20
1,ORD1003,2026-02-03,Rohit,rohit45@gmail.com,9280491167.0,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20.0,Card,Pending,2026-02-09,24995.0,19996.00,3999.20
2,ORD1004,2026-05-06,Amit,amit6@gmail.com,9943310925.0,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,5.0,COD,Returned,2026-05-08,5997.0,5697.15,1139.43
5,ORD1007,2026-02-10,Rahul,rahul82@gmail.com,9517780193.0,Mumbai,Maharashtra,Mouse,Electronics,3.0,499.0,20.0,Wallet,Cancelled,2026-02-18,1497.0,1197.60,239.52
6,ORD1008,2026-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,Up,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,2026-02-27,39996.0,39996.00,7999.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,ORD1608,2026-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,Up,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,2026-02-27,39996.0,39996.00,7999.20
520,ORD1609,NaT,Rahul,rahul99@gmail.com,9552649559.0,Mumbai,Maharashtra,Bottle,Home,2.0,1499.0,0.0,Wallet,Pending,2026-03-28,2998.0,2998.00,599.60
521,ORD1610,2026-04-10,Rohit,rohit96@gmail.com,9700116928.0,Jaipur,Rajasthan,Mouse,Electronics,1.0,NaN,0.0,NetBanking,Delivered,2026-04-16,NaN,NaN,NaN
522,ORD1611,2026-01-11,Neha,neha22@gmail.com,9580304152.0,Jaipur,Rajasthan,Chair,Furniture,3.0,999.0,0.0,COD,Pending,2026-01-16,2997.0,2997.00,599.40
523,ORD1612,2026-03-03,Vikas,vikas46@gmail.com,9551158398.0,Jaipur,Rajasthan,Shoes,Fashion,3.0,999.0,5.0,COD,Cancelled,2026-03-09,2997.0,2847.15,569.43

In [29]:
# Order Month

df["Month"]=df["Order_Date"].dt.month_name()

In [30]:
df

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date,Sales,Net_Amount,Profit,Month
0,ORD1002,2026-06-30,Neha,neha82@gmail.com,9829008196.0,Delhi,Delhi,Chair,Furniture,4.0,1999.0,0.0,UPI,Pending,2026-07-03,7996.0,7996.00,1599.20,June
1,ORD1003,2026-02-03,Rohit,rohit45@gmail.com,9280491167.0,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20.0,Card,Pending,2026-02-09,24995.0,19996.00,3999.20,February
2,ORD1004,2026-05-06,Amit,amit6@gmail.com,9943310925.0,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,5.0,COD,Returned,2026-05-08,5997.0,5697.15,1139.43,May
5,ORD1007,2026-02-10,Rahul,rahul82@gmail.com,9517780193.0,Mumbai,Maharashtra,Mouse,Electronics,3.0,499.0,20.0,Wallet,Cancelled,2026-02-18,1497.0,1197.60,239.52,February
6,ORD1008,2026-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,Up,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,2026-02-27,39996.0,39996.00,7999.20,February
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,ORD1608,2026-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,Up,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,2026-02-27,39996.0,39996.00,7999.20,February
520,ORD1609,NaT,Rahul,rahul99@gmail.com,9552649559.0,Mumbai,Maharashtra,Bottle,Home,2.0,1499.0,0.0,Wallet,Pending,2026-03-28,2998.0,2998.00,599.60,NaN
521,ORD1610,2026-04-10,Rohit,rohit96@gmail.com,9700116928.0,Jaipur,Rajasthan,Mouse,Electronics,1.0,NaN,0.0,NetBanking,Delivered,2026-04-16,NaN,NaN,NaN,April
522,ORD1611,2026-01-11,Neha,neha22@gmail.com,9580304152.0,Jaipur,Rajasthan,Chair,Furniture,3.0,999.0,0.0,COD,Pending,2026-01-16,2997.0,2997.00,599.40,January
523,ORD1612,2026-03-03,Vikas,vikas46@gmail.com,9551158398.0,Jaipur,Rajasthan,Shoes,Fashion,3.0,999.0,5.0,COD,Cancelled,2026-03-09,2997.0,2847.15,569.43,March

In [31]:
# Year
df["Year"]=df["Order_Date"].dt.year

In [54]:
df.shape

(380, 21)

In [32]:
df

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date,Sales,Net_Amount,Profit,Month,Year
0,ORD1002,2026-06-30,Neha,neha82@gmail.com,9829008196.0,Delhi,Delhi,Chair,Furniture,4.0,1999.0,0.0,UPI,Pending,2026-07-03,7996.0,7996.00,1599.20,June,2026.0
1,ORD1003,2026-02-03,Rohit,rohit45@gmail.com,9280491167.0,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20.0,Card,Pending,2026-02-09,24995.0,19996.00,3999.20,February,2026.0
2,ORD1004,2026-05-06,Amit,amit6@gmail.com,9943310925.0,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,5.0,COD,Returned,2026-05-08,5997.0,5697.15,1139.43,May,2026.0
5,ORD1007,2026-02-10,Rahul,rahul82@gmail.com,9517780193.0,Mumbai,Maharashtra,Mouse,Electronics,3.0,499.0,20.0,Wallet,Cancelled,2026-02-18,1497.0,1197.60,239.52,February,2026.0
6,ORD1008,2026-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,Up,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,2026-02-27,39996.0,39996.00,7999.20,February,2026.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,ORD1608,2026-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,Up,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,2026-02-27,39996.0,39996.00,7999.20,February,2026.0
520,ORD1609,NaT,Rahul,rahul99@gmail.com,9552649559.0,Mumbai,Maharashtra,Bottle,Home,2.0,1499.0,0.0,Wallet,Pending,2026-03-28,2998.0,2998.00,599.60,NaN,NaN
521,ORD1610,2026-04-10,Rohit,rohit96@gmail.com,9700116928.0,Jaipur,Rajasthan,Mouse,Electronics,1.0,NaN,0.0,NetBanking,Delivered,2026-04-16,NaN,NaN,NaN,April,2026.0
522,ORD1611,2026-01-11,Neha,neha22@gmail.com,9580304152.0,Jaipur,Rajasthan,Chair,Furniture,3.0,999.0,0.0,COD,Pending,2026-01-16,2997.0,2997.00,599.40,January,2026.0
523,ORD1612,2026-03-03,Vikas,vikas46@gmail.com,9551158398.0,Jaipur,Rajasthan,Shoes,Fashion,3.0,999.0,5.0,COD,Cancelled,2026-03-09,2997.0,2847.15,569.43,March,2026.0

In [33]:
# Weekday
df["Weekday"]=df["Order_Date"].dt.day_name()

In [34]:
df

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,...,Discount,Payment_Mode,Order_Status,Delivery_Date,Sales,Net_Amount,Profit,Month,Year,Weekday
0,ORD1002,2026-06-30,Neha,neha82@gmail.com,9829008196.0,Delhi,Delhi,Chair,Furniture,4.0,...,0.0,UPI,Pending,2026-07-03,7996.0,7996.00,1599.20,June,2026.0,Tuesday
1,ORD1003,2026-02-03,Rohit,rohit45@gmail.com,9280491167.0,Pune,Maharashtra,Watch,Fashion,5.0,...,20.0,Card,Pending,2026-02-09,24995.0,19996.00,3999.20,February,2026.0,Tuesday
2,ORD1004,2026-05-06,Amit,amit6@gmail.com,9943310925.0,Jaipur,Rajasthan,Mouse,Electronics,3.0,...,5.0,COD,Returned,2026-05-08,5997.0,5697.15,1139.43,May,2026.0,Wednesday
5,ORD1007,2026-02-10,Rahul,rahul82@gmail.com,9517780193.0,Mumbai,Maharashtra,Mouse,Electronics,3.0,...,20.0,Wallet,Cancelled,2026-02-18,1497.0,1197.60,239.52,February,2026.0,Tuesday
6,ORD1008,2026-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,Up,Mouse,Electronics,4.0,...,0.0,Card,Returned,2026-02-27,39996.0,39996.00,7999.20,February,2026.0,Tuesday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,ORD1608,2026-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,Up,Mouse,Electronics,4.0,...,0.0,Card,Returned,2026-02-27,39996.0,39996.00,7999.20,February,2026.0,Tuesday
520,ORD1609,NaT,Rahul,rahul99@gmail.com,9552649559.0,Mumbai,Maharashtra,Bottle,Home,2.0,...,0.0,Wallet,Pending,2026-03-28,2998.0,2998.00,599.60,NaN,NaN,NaN
521,ORD1610,2026-04-10,Rohit,rohit96@gmail.com,9700116928.0,Jaipur,Rajasthan,Mouse,Electronics,1.0,...,0.0,NetBanking,Delivered,2026-04-16,NaN,NaN,NaN,April,2026.0,Friday
522,ORD1611,2026-01-11,Neha,neha22@gmail.com,9580304152.0,Jaipur,Rajasthan,Chair,Furniture,3.0,...,0.0,COD,Pending,2026-01-16,2997.0,2997.00,599.40,January,2026.0,Sunday
523,ORD1612,2026-03-03,Vikas,vikas46@gmail.com,9551158398.0,Jaipur,Rajasthan,Shoes,Fashion,3.0,...,5.0,COD,Cancelled,2026-03-09,2997.0,2847.15,569.43,March,2026.0,Tuesday

In [35]:
# Final Data Validation

df.info()

<class 'pandas.DataFrame'>
Index: 380 entries, 0 to 523
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       374 non-null    str
 1   Order_Date     333 non-null    datetime64[us]
 2   Customer_Name  380 non-null    str
 3   Email          380 non-null    str
 4   Phone          380 non-null    object
 5   City           380 non-null    str
 6   State          380 non-null    str
 7   Product        380 non-null    str
 8   Category       380 non-null    str
 9   Qty            380 non-null    float64
 10  Unit_Price     343 non-null    float64
 11  Discount       380 non-null    float64
 12  Payment_Mode   380 non-null    str
 13  Order_Status   380 non-null    str
 14  Delivery_Date  378 non-null    datetime64[us]
 15  Sales          343 non-null    float64
 16  Net_Amount     343 non-null    float64
 17  Profit         343 non-null    float64
 18  Month          333 non-null    str
 19  Year           333 non-null    float64
 20  Weekday        333 non-null    str
dtypes: datetime64[us](2), float64(7), object(1), str(11)
memory usage: 95.8+ KB

In [36]:
df.isnull().sum()

Order_ID          6
Order_Date       47
Customer_Name     0
Email             0
Phone             0
City              0
State             0
Product           0
Category          0
Qty               0
Unit_Price       37
Discount          0
Payment_Mode      0
Order_Status      0
Delivery_Date     2
Sales            37
Net_Amount       37
Profit           37
Month            47
Year             47
Weekday          47
dtype: int64

In [37]:
df

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,...,Discount,Payment_Mode,Order_Status,Delivery_Date,Sales,Net_Amount,Profit,Month,Year,Weekday
0,ORD1002,2026-06-30,Neha,neha82@gmail.com,9829008196.0,Delhi,Delhi,Chair,Furniture,4.0,...,0.0,UPI,Pending,2026-07-03,7996.0,7996.00,1599.20,June,2026.0,Tuesday
1,ORD1003,2026-02-03,Rohit,rohit45@gmail.com,9280491167.0,Pune,Maharashtra,Watch,Fashion,5.0,...,20.0,Card,Pending,2026-02-09,24995.0,19996.00,3999.20,February,2026.0,Tuesday
2,ORD1004,2026-05-06,Amit,amit6@gmail.com,9943310925.0,Jaipur,Rajasthan,Mouse,Electronics,3.0,...,5.0,COD,Returned,2026-05-08,5997.0,5697.15,1139.43,May,2026.0,Wednesday
5,ORD1007,2026-02-10,Rahul,rahul82@gmail.com,9517780193.0,Mumbai,Maharashtra,Mouse,Electronics,3.0,...,20.0,Wallet,Cancelled,2026-02-18,1497.0,1197.60,239.52,February,2026.0,Tuesday
6,ORD1008,2026-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,Up,Mouse,Electronics,4.0,...,0.0,Card,Returned,2026-02-27,39996.0,39996.00,7999.20,February,2026.0,Tuesday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,ORD1608,2026-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,Up,Mouse,Electronics,4.0,...,0.0,Card,Returned,2026-02-27,39996.0,39996.00,7999.20,February,2026.0,Tuesday
520,ORD1609,NaT,Rahul,rahul99@gmail.com,9552649559.0,Mumbai,Maharashtra,Bottle,Home,2.0,...,0.0,Wallet,Pending,2026-03-28,2998.0,2998.00,599.60,NaN,NaN,NaN
521,ORD1610,2026-04-10,Rohit,rohit96@gmail.com,9700116928.0,Jaipur,Rajasthan,Mouse,Electronics,1.0,...,0.0,NetBanking,Delivered,2026-04-16,NaN,NaN,NaN,April,2026.0,Friday
522,ORD1611,2026-01-11,Neha,neha22@gmail.com,9580304152.0,Jaipur,Rajasthan,Chair,Furniture,3.0,...,0.0,COD,Pending,2026-01-16,2997.0,2997.00,599.40,January,2026.0,Sunday
523,ORD1612,2026-03-03,Vikas,vikas46@gmail.com,9551158398.0,Jaipur,Rajasthan,Shoes,Fashion,3.0,...,5.0,COD,Cancelled,2026-03-09,2997.0,2847.15,569.43,March,2026.0,Tuesday

In [38]:
df.describe()

,Order_Date,Qty,Unit_Price,Discount,Delivery_Date,Sales,Net_Amount,Profit,Year
count,333,380.000000,343.000000,380.000000,378,343.000000,343.000000,343.000000,333.0
mean,2026-04-02 17:35:08.108108,3.328947,3252.352770,7.802632,2026-04-10 08:41:54.285714,11103.664723,10249.073324,2049.814665,2026.0
min,2026-01-01 00:00:00,1.000000,499.000000,0.000000,2026-01-05 00:00:00,499.000000,399.200000,79.840000,2026.0
25%,2026-02-14 00:00:00,2.000000,999.000000,0.000000,2026-02-23 00:00:00,2599.000000,2398.400000,479.680000,2026.0
50%,2026-04-05 00:00:00,3.000000,1999.000000,5.000000,2026-04-13 00:00:00,5997.000000,5996.000000,1199.200000,2026.0
75%,2026-05-16 00:00:00,5.000000,4999.000000,15.000000,2026-05-25 00:00:00,12995.000000,12995.000000,2599.000000,2026.0
max,2026-06-30 00:00:00,5.000000,9999.000000,20.000000,2026-07-08 00:00:00,49995.000000,49995.000000,9999.000000,2026.0
std,NaN,1.458196,3026.092014,7.881075,NaN,12194.528486,11506.169779,2301.233956,0.0

In [39]:
# Step 15: Export Clean Data
df.to_csv("Ecommerce_Clean_Data.csv", index=False)

In [50]:
# Step 16: Import Data into MySQL

from sqlalchemy import create_engine
# engine=create_engine("mysql+pymysql://root:MySQL123@@localhost/ecommerce")

engine = create_engine(
    "mysql+pymysql://root:Password@localhost:'   '/ecommerce"
)

In [51]:
# Export DataFrame to MySQL

df.to_sql(
    name="orders",
    con=engine,
    if_exists="replace",
    index=False
)

380

In [53]:
df.shape

(380, 21)